using System;
using System.Threading.Tasks;
using System.IO;
using System.Linq;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using DentalID.Core.DTOs;
using DentalID.Core.Entities;
using DentalID.Core.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DentalID.Infrastructure.Services;

public class PdfReportService : IReportService
{
    public PdfReportService()
    {
        // License configuration (Community License for open source/personal use)
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<byte[]> GenerateSubjectReportAsync(Subject subject)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12).FontFamily(Fonts.SegoeUI));

                page.Header().Element(header => ComposeHeader(header, "Forensic Dental Profile"));
                
                page.Content().PaddingVertical(1, Unit.Centimetre).Column(column =>
                {
                    column.Spacing(20);

                    // Subject Details
                    column.Item().Row(row =>
                    {
                        // Photo placeholder if strictly needed, but text is key
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text(subject.FullName).FontSize(20).SemiBold();
                            c.Item().Text($"Subject ID: {subject.SubjectId}").FontSize(14).FontColor(Colors.Grey.Darken2);
                            c.Item().Text($"National ID: {subject.NationalId ?? "N/A"}");
                            c.Item().Text($"DOB: {subject.DateOfBirth?.ToString("yyyy-MM-dd") ?? "Unknown"}");
                        });
                    });

                    // Dental DNA Code
                    column.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(c => 
                    {
                        c.Item().Text("Latest Dental DNA Code").FontSize(14).SemiBold().FontColor(Colors.Blue.Medium);
                        c.Item().Text(subject.LatestDentalCode).FontFamily("Consolas").FontSize(16);
                    });

                    // Images Table
                    column.Item().Text("Dental Records").FontSize(16).SemiBold();
                    
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(100); // Date
                            columns.RelativeColumn();    // Fingerprint
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("Date");
                            header.Cell().Element(CellStyle).Text("Fingerprint Code");

                            static IContainer CellStyle(IContainer container)
                            {
                                return container.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                            }
                        });

                        foreach (var img in subject.DentalImages)
                        {
                            table.Cell().Element(CellStyle).Text(img.UploadedAt.ToString("yyyy-MM-dd"));
                            table.Cell().Element(CellStyle).Text(img.FingerprintCode ?? "N/A").FontFamily("Consolas");
                            
                            static IContainer CellStyle(IContainer container)
                            {
                                return container.PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten3);
                            }
                        }
                    });
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by DentalID - Forensic Analysis System");
                    x.Span($" | {DateTime.UtcNow:yyyy-MM-dd HH:mm}");
                });
            });
        });

        return Task.FromResult(document.GeneratePdf());
    }

    public Task<byte[]> GenerateMatchReportAsync(Subject probe, MatchCandidate candidate)
    {
        var generatedAtUtc = DateTime.UtcNow;
        var custodyHash = CalculateMatchCustodyHash(probe, candidate, generatedAtUtc);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                
                page.Header().Element(header => ComposeHeader(header, "Positive Identification Report"));

                page.Content().PaddingVertical(1, Unit.Centimetre).Column(column =>
                {
                    column.Spacing(20);

                    // Match Verdict
                    column.Item().Background(Colors.Green.Lighten5).Border(1).BorderColor(Colors.Green.Medium).Padding(15).Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("MATCH CONFIRMED").FontSize(24).Bold().FontColor(Colors.Green.Darken2);
                            c.Item().Text($"Confidence Score: {candidate.Score:P1}").FontSize(16).SemiBold();
                            c.Item().Text($"Method: {candidate.MatchMethod}").FontSize(12);
                        });
                    });

                    // Comparison Table
                    column.Item().Table(table =>
                    {
                         table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.ConstantColumn(20);
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Column(c => c.Item().Text("PROBE (Unknown)").Bold());
                            header.Cell();
                            header.Cell().Column(c => c.Item().Text("CANDIDATE (Known)").Bold());
                        });

                        table.Cell().Column(c => 
                        {
                            c.Item().Text("Unknown Subject");
                            c.Item().Text($"DNA: {probe.LatestDentalCode}").FontFamily("Consolas").FontSize(10);
                        });
                        
                        table.Cell().AlignCenter().Text("vs");

                        table.Cell().Column(c => 
                        {
                            c.Item().Text(candidate.Subject.FullName);
                            c.Item().Text($"ID: {candidate.Subject.SubjectId}");
                            c.Item().Text($"DNA: {candidate.Subject.LatestDentalCode}").FontFamily("Consolas").FontSize(10);
                        });
                    });

                    // Match Details
                    if (candidate.MatchDetails.Count > 0)
                    {
                        column.Item().Text("Match Breakdown").FontSize(16).SemiBold();
                        foreach(var detail in candidate.MatchDetails)
                        {
                             column.Item().Text($"{detail.Key}: {detail.Value}");
                        }
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by DentalID - Forensic Analysis System");
                    x.Span($" | Generated UTC: {generatedAtUtc:yyyy-MM-dd HH:mm:ss}");
                    x.Span($" | Chain of Custody Hash: {custodyHash}");
                });
            });
        });

        return Task.FromResult(document.GeneratePdf());
    }

    private static string CalculateMatchCustodyHash(Subject probe, MatchCandidate candidate, DateTime generatedAtUtc)
    {
        var details = candidate.MatchDetails ?? new Dictionary<string, double>();
        var builder = new StringBuilder();
        builder.Append(probe.SubjectId ?? probe.FullName ?? "PROBE");
        builder.Append('|');
        builder.Append(candidate.Subject.SubjectId ?? candidate.Subject.FullName ?? "CANDIDATE");
        builder.Append('|');
        builder.Append(candidate.Score.ToString("F6", CultureInfo.InvariantCulture));
        builder.Append('|');
        builder.Append(candidate.MatchMethod ?? string.Empty);

        foreach (var detail in details.OrderBy(x => x.Key, StringComparer.Ordinal))
        {
            builder.Append('|');
            builder.Append(detail.Key);
            builder.Append(':');
            builder.Append(detail.Value.ToString("F6", CultureInfo.InvariantCulture));
        }

        builder.Append('|');
        builder.Append(generatedAtUtc.ToString("O", CultureInfo.InvariantCulture));

        using var sha256 = SHA256.Create();
        var hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(builder.ToString()));
        return Convert.ToHexString(hashBytes)[..12];
    }

    private void ComposeHeader(IContainer container, string title)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text(title).FontSize(24).SemiBold().FontColor(Colors.Blue.Darken2);
                column.Item().Text("Forensic Dental Analysis Lab").FontSize(10);
            });
        });
    }

    public async Task<byte[]> GenerateLabReportAsync(AnalysisResult result, Subject subject, string imagePath)
    {
        return await Task.Run(() =>
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily(Fonts.SegoeUI));

                    page.Header().Element(header => ComposeHeader(header, "Forensic Lab Analysis"));

                    page.Content().PaddingVertical(1, Unit.Centimetre).Element(c => ComposeLabContent(c, result, subject, imagePath));
                    
                    page.Footer().Element(f => ComposeLabFooter(f, result, subject));
                });
            });
            return document.GeneratePdf();
        });
    }

    private void ComposeLabContent(IContainer container, AnalysisResult result, Subject subject, string imagePath)
    {
        container.Column(column =>
        {
            column.Spacing(20);

            // 0. Forensic Alerts (Critical)
            if (result.Flags != null && result.Flags.Count > 0)
            {
                column.Item().Border(1).BorderColor(Colors.Red.Medium).Background(Colors.Red.Lighten5).Padding(10).Column(c => 
                {
                    c.Item().Row(r => 
                    {
                        r.AutoItem().Text("⚠ FORENSIC ALERTS DETECTED").Bold().FontColor(Colors.Red.Medium).FontSize(14);
                    });
                    
                    foreach (var flag in result.Flags)
                    {
                        c.Item().Text($"• {flag}").FontColor(Colors.Red.Darken2);
                    }
                });
            }

            // 1. Subject Info
            column.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("Subject Information").Bold();
                    c.Item().Text($"Name: {subject?.FullName ?? "Unknown"}");
                    c.Item().Text($"ID: {subject?.SubjectId ?? "N/A"}");
                });
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("AI Estimates").Bold();
                    c.Item().Text($"Est. Age: {result.EstimatedAge?.ToString() ?? "N/A"}");
                    c.Item().Text($"Est. Gender: {result.EstimatedGender ?? "N/A"}");
                });
            });

            // 2. X-Ray Image
            if (File.Exists(imagePath))
            {
                column.Item().Text("Radiographic Evidence").Bold();
                // Ensure image fits within page width, maintain aspect ratio
                column.Item().Image(imagePath).FitArea(); 
            }

            // 3. Odontogram (Vector)
            column.Item().Text("Odontogram Chart (FDI)").Bold();
            column.Item().Element(c => ComposeOdontogram(c, result));

            // 4. Findings Table
            column.Item().Text("Detailed Findings").Bold();
            column.Item().Table(table =>
            {
                // Definitions
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(80); // Tooth #
                    columns.RelativeColumn();   // Condition
                    columns.ConstantColumn(80); // Confidence
                });

                // Header
                table.Header(header =>
                {
                    header.Cell().Element(CellStyle).Text("Tooth (FDI)");
                    header.Cell().Element(CellStyle).Text("Condition / Pathology");
                    header.Cell().Element(CellStyle).Text("Confidence");

                    static IContainer CellStyle(IContainer c) => c.DefaultTextStyle(x => x.SemiBold()).BorderBottom(1).BorderColor(Colors.Black).PaddingVertical(5);
                });

                // Data
                // Group pathologies by tooth
                var allDetections = result.Teeth.OrderBy(t => t.FdiNumber).ToList();
                
                foreach (var tooth in allDetections)
                {
                    var pathologies = result.Pathologies.Where(p => p.ToothNumber == tooth.FdiNumber).ToList();
                    string condition = pathologies.Any() ? string.Join(", ", pathologies.Select(p => p.ClassName)) : "Healthy";
                    string confidence = $"{tooth.Confidence:P0}";
                    
                    if (pathologies.Any())
                    {
                        // Highlight pathologies
                        table.Cell().Element(CellStyleRed).Text(tooth.FdiNumber.ToString());
                        table.Cell().Element(CellStyleRed).Text(condition);
                        table.Cell().Element(CellStyleRed).Text(confidence);
                    }
                    else
                    {
                        table.Cell().Element(CellStyle).Text(tooth.FdiNumber.ToString());
                        table.Cell().Element(CellStyle).Text(condition);
                        table.Cell().Element(CellStyle).Text(confidence);
                    }

                    static IContainer CellStyle(IContainer c) => c.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
                    static IContainer CellStyleRed(IContainer c) => c.BorderBottom(1).BorderColor(Colors.Red.Lighten2).Background(Colors.Red.Lighten4).PaddingVertical(5);
                }
            });
        });
    }

    private void ComposeOdontogram(IContainer container, AnalysisResult result)
    {
        // Simple simplified vector chart for PDF
        // Draw 32 boxes with text
        container.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(col => 
        {
            // Upper
            col.Item().Row(row => 
            {
                // Q1: 18-11
                row.RelativeItem().AlignRight().Row(r => 
                {
                    for (int i=18; i>=11; i--) DrawTooth(r, i, result);
                });
                
                // Gap
                row.ConstantItem(10);

                // Q2: 21-28
                row.RelativeItem().AlignLeft().Row(r => 
                {
                    for (int i=21; i<=28; i++) DrawTooth(r, i, result);
                });
            });

            col.Item().Height(5); // Spacing

            // Lower
            col.Item().Row(row => 
            {
                // Q4: 48-41
                row.RelativeItem().AlignRight().Row(r => 
                {
                    for (int i=48; i>=41; i--) DrawTooth(r, i, result);
                });

                // Gap
                row.ConstantItem(10);
                
                // Q3: 31-38
                row.RelativeItem().AlignLeft().Row(r => 
                {
                    for (int i=31; i<=38; i++) DrawTooth(r, i, result);
                });
            });
        });
    }

    private void DrawTooth(QuestPDF.Fluent.RowDescriptor row, int fdi, AnalysisResult result)
    {
        // Check status
        var pathologies = result.Pathologies.Where(p => p.ToothNumber == fdi).ToList();
        bool isAffected = pathologies.Any();
        string color = isAffected ? Colors.Red.Medium : Colors.White;
        string textColor = isAffected ? Colors.White : Colors.Black;

        row.ConstantItem(25).Height(30).Border(1).BorderColor(Colors.Grey.Medium).Background(color).Column(c => 
        {
            c.Item().AlignCenter().Text(fdi.ToString()).FontSize(8).FontColor(textColor);
        });
    }

    private byte[] GenerateQrSeal(string payload)
    {
        using var qrGenerator = new QRCoder.QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(payload, QRCoder.QRCodeGenerator.ECCLevel.Q);
        using var qrCode = new QRCoder.PngByteQRCode(qrCodeData);
        return qrCode.GetGraphic(20);
    }

    private string CalculateForensicHash(AnalysisResult result, Subject subject)
    {
        // Create a unique string representing the core findings
        // USE INVARIANT CULTURE for all numbers to ensure hash consistency across machines
        var sb = new System.Text.StringBuilder();
        sb.Append(subject.Id);
        sb.Append("|");
        sb.Append(subject.SubjectId); // Bind to Case ID
        sb.Append("|");
        // REMOVED ProcessingTimeMs as it is metadata, not forensic evidence
        
        foreach(var t in result.Teeth.OrderBy(x => x.FdiNumber))
            sb.Append($"{t.FdiNumber}:{t.Confidence.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)}|");
            
        foreach(var p in result.Pathologies.OrderBy(x => x.ClassName).ThenBy(x => x.ToothNumber))
            sb.Append($"{p.ClassName}:{p.ToothNumber}:{p.Confidence.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)}|");
            
        // Include flags in hash for integrity
        if (result.Flags != null)
        {
            foreach(var f in result.Flags.OrderBy(x => x)) 
                sb.Append($"{f}|");
        }
            
        using var sha256 = System.Security.Cryptography.SHA256.Create();
        byte[] bytes = sha256.ComputeHash(System.Text.Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(bytes);
    }

    private void ComposeLabFooter(IContainer container, AnalysisResult result, Subject subject)
    {
        var hash = CalculateForensicHash(result, subject);
        var sealPayload = $"DentalID|{hash}|{DateTime.UtcNow:O}";
        var qrBytes = GenerateQrSeal(sealPayload);

        container.Row(row =>
        {
            // Left: Page Info
            row.RelativeItem().Column(c =>
            {
                c.Item().Text(x =>
                {
                    x.Span("Page ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
                c.Item().Text($"Seal Hash: {hash}").FontSize(8).FontColor(Colors.Grey.Medium);
            });

            // Right: Digital Seal
            row.ConstantItem(60).AlignRight().Image(qrBytes);
        });
    }

    public async Task GenerateCaseReportAsync(Case c, string outputPath)
    {
        await Task.Run(() =>
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12).FontFamily(Fonts.SegoeUI));

                    page.Header().Element(header => ComposeHeader(header, $"CASE REPORT: {c.CaseNumber}"));

                    page.Content().PaddingVertical(1, Unit.Centimetre).Column(x =>
                    {
                        x.Spacing(20);

                        // Case Details
                        x.Item().Text("Case Details").FontSize(18).SemiBold();
                        x.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(100);
                                columns.RelativeColumn();
                            });

                            table.Cell().Text("Title:").SemiBold();
                            table.Cell().Text(c.Title);

                            table.Cell().Text("Status:").SemiBold();
                            table.Cell().Text(c.Status.ToString());

                            table.Cell().Text("Date:").SemiBold();
                            table.Cell().Text(c.IncidentDate?.ToString("yyyy-MM-dd") ?? "N/A");
                            
                            table.Cell().Text("Location:").SemiBold();
                            table.Cell().Text(c.Location ?? "N/A");

                            table.Cell().Text("Description:").SemiBold();
                            table.Cell().Text(c.Description ?? "N/A");
                        });

                        // Evidence / Matches
                        if (c.Matches != null && c.Matches.Count > 0)
                        {
                            x.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            x.Item().Text("Linked Evidence (Matches)").FontSize(18).SemiBold();

                            foreach (var match in c.Matches)
                            {
                                x.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(col =>
                                {
                                    col.Item().Text($"Match ID: {match.Id}").FontSize(10).FontColor(Colors.Grey.Medium);
                                    col.Item().Text($"Subject: {match.MatchedSubject?.FullName ?? "Unknown"}").Bold();
                                    col.Item().Text($"Confidence: {match.ConfidenceScore:P2}").FontColor(Colors.Green.Medium);
                                    col.Item().Text($"Date: {match.ConfirmedAt?.ToString("yyyy-MM-dd HH:mm") ?? "N/A"}");
                                });
                            }
                        }
                        else
                        {
                            x.Item().Text("No linked evidence.").Italic().FontColor(Colors.Grey.Medium);
                        }

                        // Result
                        if (c.Result != null)
                        {
                            x.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            x.Item().Text("Conclusion").FontSize(18).SemiBold();
                            x.Item().Text(c.Result);
                        }
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by DentalID - Forensic Analysis System");
                        x.Span($" | {DateTime.UtcNow:yyyy-MM-dd HH:mm}");
                    });
                });
            })
            .GeneratePdf(outputPath);
        });
    }
}


